In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
import statistics
from collections import Counter
from matplotlib.backends.backend_pdf import PdfPages



from tensorflow import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Activation

In [29]:
data = mnist.load_data()
print(data[0])

(array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ...,

In [30]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [31]:
# (Num of Rows (num of images), dim of the image (row), dim of the image (col))
x_train.shape

(60000, 28, 28)

In [13]:
y_train.shape

(60000,)

In [32]:
x_train_final = x_train.reshape((-1, 784))
x_train_final.shape
print(x_train_final)
print("-----------------------------------")
# ---------------
x_test_final = x_test.reshape((-1, 784))
x_test_final.shape
print(x_test_final)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
-----------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [33]:
# Normalization (255 --> RGB)
x_train_final = x_train_final/255
x_test_final = x_test_final/255
print(x_train_final)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [34]:
# Start Model
model = Sequential()
# 10 --> cause it's ten classes (ten labels)
model.add(Dense(10, input_shape = (784,)))
model.add(Activation('softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [35]:
model.compile(optimizer = 'sgd', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [36]:
results = model.fit(x=x_train_final, y=y_train, shuffle=True, batch_size=16,epochs = 30, validation_data=(x_test_final, y_test))

Epoch 1/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.7773 - loss: 0.8936 - val_accuracy: 0.8952 - val_loss: 0.4004
Epoch 2/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step - accuracy: 0.8882 - loss: 0.4090 - val_accuracy: 0.9056 - val_loss: 0.3496
Epoch 3/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8989 - loss: 0.3618 - val_accuracy: 0.9109 - val_loss: 0.3288
Epoch 4/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 10s 1ms/step - accuracy: 0.9048 - loss: 0.3423 - val_accuracy: 0.9133 - val_loss: 0.3160
Epoch 5/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.9075 - loss: 0.3310 - val_accuracy: 0.9152 - val_loss: 0.3073
Epoch 6/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.9106 - loss: 0.3254 - val_accuracy: 0.9168 - val_loss: 0.3011
Epoch 7/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.9137 - loss: 0.3073 - val_accuracy: 0.9180 - val_loss: 0.2952
Epoch 8/30
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 9s 1ms/step - accuracy: 0.9156 - loss: 0.306